# config.yaml

data_and_features:
    save_folder: "Results/"
    good_folder: "../../train_cut/engine1_good/"
    broken_folder: "../../train_cut/engine2_broken/"
    heavy_folder:  "../../train_cut/engine3_heavyload/"
    model_save_folder: "saved_models/"
             
    Fs: 44100

    selected_feature: "FFT" # FFT, STFT, MelEner, MelLog
    apply_xai: True # False True
    num_hidd_dim: 200   
    
    
    #Mel energy
    nfft_mle: 2048
    hop_len_mle: 512
    mle_n_frames: 5
    
        
    #Mel Log
    win_len_mel: 8820
    hop_len_mel: 4410
    
    
    # STFT
    win_len_stft: 4410 # size in samples 
    overlap_l_stft: 2205
    
    # time features
    time_frame_x: 50
    time_frame_y: 50
    
    to_save_res: True  # False   
    to_save_model: True


model_optimization:
  test_size: 0.15
  batch_size: 32
  n_epochs: 80
  lrate: 0.0005
  device: "cuda"


