# config.yaml

data_and_features:
    save_folder: "Results/"
    good_folder: "../../train_cut/engine1_good/"
    broken_folder: "../../train_cut/engine2_broken/"
    heavy_folder:  "../../train_cut/engine3_heavyload/"
    model_save_folder: "saved_models/"
             
    Fs: 44100
     
    selected_feature: "FFT" # FFT, STFT, MelEner, MelLog 
    apply_xai: False # False True
    num_hidd_dim: 200 
    
    #framming settings
    #frame_len: 2500 
    #frame_move_len: 500
    
    #Mel energy
    nfft_mle: 2048
    hop_len_mle: 512
    mle_n_frames: 5
    
        
    #Mel Log
    win_len_mel: 4410
    hop_len_mel: 2205
    
    
    # STFT
    win_len_stft: 4410 
    overlap_l_stft: 2205
    
    # time features
    time_frame_x: 50
    time_frame_y: 50
    
    to_save_res: True  # False   
    to_save_model: True

model_optimization:
  test_size: 0.2
  batch_size: 32
  n_epochs: 40
  lrate: 0.0002
  device: "cpu"


